### ISSUE TITLE
the issue is areise poem.txt

### ISSUE THREAD

**Issue by codingkarovikas** [vikasverma-here/text#8]
please review the line number two there is mistekly written bariyarpur but it is not a bariyarpur

**Comment by vikasverma-here** [comment]
good nice to see for you effort is very nice

**Comment by codingkarovikas** [comment]
thabku

**Comment by vikasverma-here** [comment]
#8 nice  to meet you

**Comment by codingkarovikas** [comment]
cna you suggest me something

**Comment by vikasverma-here** [comment]
#8 nothing
